header = "# caNanoLab DOI \n"
separator = "-------------------------- \n"
tableheader = "| Property | Value | \n"
tableseparator = "|----------|---------| \n"
fileheader = "| File Name | File Type | \n"